---
title: Barefoot Horse Farrier
timezone: UTC
collections:
  callouts:
    title: Callouts
    output: true
  mission-statement:
    title: Mission Statement
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'THRIVE Equine Hoof Care.

'
baseurl: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- bourbon
- neat
sass:
  sass_dir: _sass
